# Generated by Django 3.2.6 on 2021-11-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField()),
                ('name', models.CharField(max_length=20, verbose_name='目录名称')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField()),
                ('title', models.CharField(max_length=30, verbose_name='文章标题')),
                ('content', models.TextField(max_length=2000, verbose_name='文章内容')),
                ('page_view', models.IntegerField(verbose_name='浏览量')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='所属栏目')),
                ('tag', models.ManyToManyField(to='api.Tag', verbose_name='标签')),
            ],
        ),
    ]
