# Generated by Django 3.2.6 on 2021-11-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[('已发布', 1), ('未发布', 0)], default=1, verbose_name='发布状态'),
        ),
    ]
