# Generated by Django 3.2.6 on 2021-11-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_article_page_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=1636274413.49416, verbose_name='发布时间'),
        ),
    ]
