# Generated by Django 3.2.6 on 2021-11-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_article_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=1636274416.7369092, verbose_name='发布时间'),
        ),
    ]
