# Generated by Django 3.2.6 on 2021-11-10 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211107_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(1, '已发布'), (0, '未发布')], default=1, verbose_name='发布状态'),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('content', models.TextField(max_length=2000, verbose_name='文章内容')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article', verbose_name='目标文章')),
            ],
        ),
    ]
